


-- Steps:  

-- 1. create a catalog table to verify the table & columns descriptions generated by your SP
  create or replace table ai_generated_description_catalog
  (
      domain varchar,
      description varchar, 
      name varchar,
      database_name varchar,
      schema_name varchar,
      table_name varchar,
      ingested_timestamp timestamp default current_timestamp()
   );